### ISSUE TITLE
About NHANES_20172020

### ISSUE THREAD

**Issue by FlowerDance916** [jamesjiadazhan/dietaryindex_NHANES#1]
Thanks for your contribution. When calculating HEI2020 and HEI2015 using [NHANES_20172020.Rda]， an error occurred： Column `WTDRD1` doesn't exist. Then， I replaced the variable name "WTDRD1PP" and "WTDR2DPP" with `WTDRD1` and `WTDRD2`. I wonder if this is correct. In addition， assuming the above operation is correct， I calculated 'HEI2015' and 'HEI2020' and found that they were the same. I calculated 'HEI2015' and 'HEI2020' using [NHANES_20172018.Rda]. These results were similar but slightly different. I wonder what to do next. Thank you.
![image](https://github.com/jamesjiadazhan/dietaryindex_NHANES/assets/94223378/6c6df811-6931-42b0-ad0a-6b7a88380d7a)

**Comment by jamesjiadazhan** [comment]
Thanks a lot for this feedback! The error was because NHANES 2017-2020 used a "WTDRD1PP" instead of "WTDRD1" in other years, like NHANES 17-18. Actually, "WTDRD1" column was not functioning at all, so I just removed it to avoid the bug. Thus, it is totally fine if you rename the variable.

I updated the HEI2020_NHANES_FPED function. There was an issue if you calculated HEI2020 using the 2-day data. Now it is fixed. The results of HEI2020 and HEI2015 should be slightly different because HEI2020 includes toddlers (those with age < 2 years but >= 1 years) while HEI2015 doesn't.

Do you mind installing the package again and rerunning the codes? I want to make sure there is no bug now.

**Comment by FlowerDance916** [comment]
Thank you. The problem has been solved.
